// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Tasko.Server.Context.Data.Context;
using Tasko.Server.Context.Data.Models;

#nullable disable

namespace Tasko.Server.Context.Data.Context.Configurations
{
    public partial class RoleConfiguration : IEntityTypeConfiguration<Role>
    {
        public void Configure(EntityTypeBuilder<Role> entity)
        {
            entity.Property(e => e.Id)
            .HasColumnOrder(0)
            .HasDefaultValueSql("(newid())");
            entity.Property(e => e.Name).HasColumnOrder(1);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Role> entity);
    }
}
