version: '3.4'

volumes:
    rabbitmq_data:
    rabbitmq_log:

networks:
  rabbitmq:
  backend:
  frontend:

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - rabbitmq 

  tasko.authservice:
    container_name: tasko-auth-service
    image: ${DOCKER_REGISTRY-}taskoauthservice
    build:
      context: .
      dockerfile: Tasko.AuthService/Dockerfile
    networks:
    - backend

  tasko.userservice:
    container_name: tasko-user-service
    image: ${DOCKER_REGISTRY-}taskouserservice
    build:
      context: .
      dockerfile: Tasko.UserService/Dockerfile
    networks:
    - backend

  tasko.roleservice:
    container_name: tasko-role-service
    image: ${DOCKER_REGISTRY-}taskoroleservice
    build:
      context: .
      dockerfile: Tasko.RoleService/Dockerfile
    networks:
    - backend

  tasko.boardservice:
    container_name: tasko-board-service
    image: ${DOCKER_REGISTRY-}taskoboardservice
    build:
      context: .
      dockerfile: Tasko.BoardService/Dockerfile
    networks:
    - backend

  tasko.permissionservice:
    container_name: tasko-permission-service
    image: ${DOCKER_REGISTRY-}taskopermissionservice
    build:
      context: .
      dockerfile: Tasko.PermissionService/Dockerfile
    networks:
    - backend

  tasko.apigateway:
    container_name: tasko-api-gateway
    image: ${DOCKER_REGISTRY-}taskoapigateway
    build:
      context: .
      dockerfile: Tasko.ApiGateway/Dockerfile
    ports:
    - 8001:80
    networks:
    - backend