global using AutoMapper;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Microsoft.AspNetCore.Authorization;
global using MongoDB.Driver;
global using Tasko.Domains.Models.Structural.Providers;
global using Tasko.General.Validations;
global using Tasko.Service.Infrastructure.Extensions;
global using Tasko.Service.Infrastructure.Repositories;
global using IRouteHandler = Tasko.General.Interfaces.IRouteHandler;
