// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Tasko.Server.Context.Data.Models;

public partial class User
{
    [Key]
    public Guid GlobalGuid { get; set; }

    public Guid PhoneGuid { get; set; }

    public Guid EmailGuid { get; set; }

    public Guid Role { get; set; }

    [StringLength(255)]
    public string FirstName { get; set; } = null!;

    [StringLength(512)]
    public string PasswordHash { get; set; } = null!;

    [StringLength(255)]
    public string LastName { get; set; } = null!;

    [StringLength(255)]
    public string Patronymic { get; set; } = null!;

    [StringLength(4000)]
    public string? Photo { get; set; }

    [StringLength(2000)]
    public string? About { get; set; }

    [Column(TypeName = "date")]
    public DateTime LastOnline { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("Role")]
    [InverseProperty("Users")]
    public virtual Role RoleNavigation { get; set; } = null!;
}